### ISSUE TITLE
Investigate the possibility of video integration with Whereby api

### ISSUE THREAD

**Issue by laurasstephan** [rodrigogs/barracao-digital#60]
https://whereby.com/information/product-api/

**Comment by kuroski** [comment]
Hello @laurasstephan.
Just questioning if this task will not close this one:
https://github.com/rodrigogs/barracao-digital/issues/61

?? The `Opentok integration` is enough, or do we still need the Whereby integration?

**Comment by laurasstephan** [comment]
Sure, Opentok is enough! This was an idea that we had before we find Opentok :D

**Comment by kuroski** [comment]
Awesome ^^
