### ISSUE TITLE
Change label of the buttom "Iniciar atendimento"

### ISSUE THREAD

**Issue by laurasstephan** [rodrigogs/barracao-digital#67]
Some feedback from the doctors:
After logging in on the platform, they did not understand they had to click on "Iniciar atendimento" to become available. They thought they had to click on this button only then they see that there is a patient was waiting. So maybe instead of "Iniciar atendimento" we could change the label of the button to "Entrar on-line"/"Ficar on-line"? (Open to suggestions)

**Comment by kuroski** [comment]
Ok, to you prefer:
- Ficar on-line / Ficar offline

Instead of:
- Iniciar atendimento / Parar atendimento

??

When we confirm the text, I can change that quickly =D
@laurasstephan 

And I don't have a better suggestion =D

**Comment by laurasstephan** [comment]
Yes! Ficar on-line / Ficar off-line sounds good.
