### ISSUE TITLE
Patient list bug

### ISSUE THREAD

**Issue by pedropiccaro** [rodrigogs/barracao-digital#69]
The patient list filters presents some bugs
<img width="1261" alt="Captura de Tela 2020-05-05 às 21 28 12" src="https://user-images.githubusercontent.com/11322698/81128502-c330da80-8f17-11ea-99b4-ffafa4cfa44d.png">

**Comment by kuroski** [comment]
Hello @pedropiccaro 
Could you confirm if now its ok? Since we changed a bit the filters:

![image](https://user-images.githubusercontent.com/1855125/81496213-51111a80-92b6-11ea-9cad-ec04785e3a01.png)

**Comment by rodrigogs** [comment]
This filter was completely rewritten.
