### ISSUE TITLE
Google keyboard bug in the chat 

### ISSUE THREAD

**Issue by laurasstephan** [rodrigogs/barracao-digital#72]
The same bug that was happening in the patient Name field is now happening in the chat, on my Chrome for Android. If I don't type space after the word, it doesn't allow me to send the message (as if the field is blank). 
E.g.:
"Hi" --> doesn't work
"Hi "--> works
If I write a sentence, without space in the end, only the last word will be suppressed.
"How are you" --> will be sent as How are
"How are you "--> works fine

**Comment by francobrunoc** [comment]
Bug not detected after tests on android. It is probably already solved.
