### ISSUE TITLE
allow patients to sinalize preferred time frame to talk with the doctor  

### ISSUE THREAD

**Issue by pedropiccaro** [rodrigogs/barracao-digital#86]
options:
tomorrow 8-10h
tomorrow 20-22h

**Comment by laurasstephan** [comment]
Update: We had another idea that will probably be easier;

This is the message we have now when no doctors are available: 
![Captura de Tela 2020-06-21 às 10 48 21](https://user-images.githubusercontent.com/63982998/85213056-70b75a80-b3ad-11ea-8729-db30c665ab35.png)

Let's change to this one: 

**_xxx_, nossa equipe está sobrecarregada no momento, mas seu nome está na nossa lista de espera. Você tem duas opções:
1) Seguir aguardando com o navegador aberto nessa página para ser notificado quando o atendimento normalizar, ou
2) Anotar sua senha de retorno (_mostrar senha_) e voltar aqui no site entre 18-21h, que é quando temos um maior número de médicos voluntários on-line.

Obrigado pela paciência!**

**Comment by laurasstephan** [comment]
Issue #90 refers to this so we can change the message ourselves.
